CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, role),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES app_users (id)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    category VARCHAR(80) NOT NULL,
    location VARCHAR(160) NOT NULL,
    remote BOOLEAN NOT NULL,
    status VARCHAR(16) NOT NULL,
    asker_id BIGINT NOT NULL,
    assigned_doer_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tasks_asker
        FOREIGN KEY (asker_id) REFERENCES app_users (id),
    CONSTRAINT fk_tasks_assigned_doer
        FOREIGN KEY (assigned_doer_id) REFERENCES app_users (id)
);

CREATE TABLE task_drops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    doer_id BIGINT NOT NULL,
    dropped_at TIMESTAMP WITH TIME ZONE NOT NULL,
    rating INTEGER,
    review VARCHAR(2000),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_drops_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_drops_doer
        FOREIGN KEY (doer_id) REFERENCES app_users (id)
);

CREATE TABLE status_update_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    response VARCHAR(2000),
    responded_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_status_update_requests_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE TABLE task_assistance_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL UNIQUE,
    requesting_doer_id BIGINT NOT NULL,
    helper_id BIGINT,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    offered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_assistance_requests_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_assistance_requests_requesting_doer
        FOREIGN KEY (requesting_doer_id) REFERENCES app_users (id),
    CONSTRAINT fk_task_assistance_requests_helper
        FOREIGN KEY (helper_id) REFERENCES app_users (id)
);

CREATE TABLE task_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    asking_doer_id BIGINT NOT NULL,
    question VARCHAR(2000) NOT NULL,
    asked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    answer VARCHAR(2000),
    answered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_questions_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_questions_asking_doer
        FOREIGN KEY (asking_doer_id) REFERENCES app_users (id)
);

CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    task_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL,
    type VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_user_notifications_recipient
        FOREIGN KEY (recipient_id) REFERENCES app_users (id),
    CONSTRAINT fk_user_notifications_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_user_notifications_actor
        FOREIGN KEY (actor_id) REFERENCES app_users (id)
);
