CREATE TABLE task_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL UNIQUE,
    doer_id BIGINT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review VARCHAR(2000),
    reviewed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_reviews_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_reviews_doer
        FOREIGN KEY (doer_id) REFERENCES app_users (id)
);
