CREATE TABLE task_chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    primary_doer_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_chat_rooms_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_chat_rooms_primary_doer
        FOREIGN KEY (primary_doer_id) REFERENCES app_users (id)
);

CREATE INDEX idx_task_chat_rooms_active_task
    ON task_chat_rooms (task_id)
    WHERE closed_at IS NULL;

CREATE TABLE task_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message VARCHAR(2000) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_task_chat_messages_room
        FOREIGN KEY (room_id) REFERENCES task_chat_rooms (id),
    CONSTRAINT fk_task_chat_messages_sender
        FOREIGN KEY (sender_id) REFERENCES app_users (id)
);

CREATE INDEX idx_task_chat_messages_room_sent
    ON task_chat_messages (room_id, sent_at, id);
