spring:
  application:
    name: taskit-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskit}
    username: ${SPRING_DATASOURCE_USERNAME:taskit}
    password: ${SPRING_DATASOURCE_PASSWORD:taskit}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui
